### ISSUE TITLE
DwC_metadata

### ISSUE THREAD

**Issue by DrMattG** [LivingNorway/LivingNorwayR#17]
@joechip90 I have made a minor (but major for me!) step forward on creating what I am calling the "metadata" class. I seem to be forced in to making two steps though - is there a neater way to code this so that I can initialise and call the function within the same line (probably something obvious but I am not sure). 

`DwC_metadata<-R6::R6Class(
  classname = "metadata",
  public = list(
    metadata=NA,
    initialize=function(metadata){
        self$metadata<-metadata},
##This function just reads the markdown as txt and cleans it up a bit for use later as XML 
    get_metadata = function(filepath) {
      x = readr::read_lines(filepath) # read markdown using readlines
      rng = grep("^---$", x)
      rng = rng + c(1, -1)
      x = x[rng[1]:rng[2]]
      names(x) = gsub("(.*):.*", "\\1", x)
      x = gsub(".*: (.*)", "\\1", x)
      return(as.list(x))
    }
    ))
#Example
test<-DwC_metadata$new(metadata = NA)
test$get_metadata(filepath= filepath_to_Rmd)

`

**Comment by joechip90** [comment]
Hi Matt! That looks pretty good. A couple of minor stylistic points though. We might want to rename the class object to DwCMetadata so that it is consistent with the naming convention of the other DwC classes (DwCGeneric, DwCTerm etc.). Also the classname argument in the R6Class function needs to mimic the name of the object used to store the class name (i.e. DwCMetadata) so the classname argument needs to be "DwCMetadata". Otherwise potential users will need to remember a different name when they want to instantiate objects of that class.

We probably also want the initialize function to work on file-paths I guess rather than metadata objects directly. So probably the initialize function should probably just call the get_metadata function (which, to be stylistically consistent we might want to think about renaming getMetadata) and pass its argument to it.

I'll try and get the generic class committed today so you'll have a reference

**Comment by ErlendNilsen** [comment]
@DrMattG Seems like the last line of code in DwCMetadata.R is causing problems. Change filepath?

**Comment by DrMattG** [comment]
@ErlendNilsen Yeah - Joe and I discussed having another look at the DwCMetadata class this morning as the generic nature of it opens up too many potential problems. We will talk next week about it (that "we" includes you if you are free).

**Comment by DrMattG** [comment]
#23

**Comment by joechip90** [comment]
Closing this issue because it is no longer relevant now that we are overhauling the way we handle metadata
